name = "Paperback"
license = "MIT"
licenselink = "https://github.com/dashdashzako/paperback/blob/master/LICENSE.md"
description = "Minimalist theme for Hugo."
homepage = "https://github.com/dashdashzako/paperback"
tags = ["minimalist", "reading", "sepia", "blog"]
features = ["blog"]
min_version = 0.57

[author]
  name = "dashdashzako"
  homepage = "https://github.com/dashdashzako"
