name = "Paperback"
license = "MIT"
licenselink = "https://github.com/damiencaselli/paperback/blob/master/LICENSE.md"
description = "Minimalist theme for Hugo."
homepage = "https://github.com/damiencaselli/paperback"
tags = ["minimalist", "reading", "sepia", "blog"]
features = ["blog"]
min_version = 0.15

[author]
  name = "Damien Caselli"
  homepage = "https://github.com/damiencaselli"
